name: get_tracker_list

on:
    schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get latest tracker list and compress
      run: |
        bash -c "./trackers.sh . trackers.list"
        find . -name "*trackers*"

    - name: Add list to old directory
      run: | 
        cat trackers.list >> ./old/all-trackers.list
        sort -u ./old/all-trackers.list > ./old/all-trackers.list
        bzip2 -9 -f -k ./old/all-trackers.list ./old/all-trackers.list.bz2

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add trackers.list ./old/*
        git commit -m "New list every day (:"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
